# hypro.sub
universe = vanilla
workflow = hypro-pelican

# IMPORTANT! Require execute servers that have access to Staging
requirements = (TARGET.HasCHTCStaging == TRUE)

# Specify executable
executable = $ENV(CHTC_REPO)/source/$(workflow)2/hypro.sh

# NOTE: Leading whitespace is trimmed from each line
arguments  = --date $(flight_date) \
   --site-code $(site_code) \
   --project-code $(project_code) \
   --project-name $(project_name) \
   --image-number $(image_number) \
   --line-number $(line_number) \
   --swir-pixel-size $(swir_pixel_size)

# TODO: Spaces in site & project names; tried escaped double quotes (`\"`) but then the output directory has quotes in its name...

if defined site_name
   arguments=$(arguments) --site-name $(site_name)
endif

if defined raw_basename
   arguments=$(arguments) --raw-basename $(raw_basename)
endif

if defined fovexp
   arguments=$(arguments) --fovexp $(fovexp)
endif

if defined target_sampling
   arguments=$(arguments) --target-sampling $(target_sampling)
endif

if defined vdatum
   arguments=$(arguments) --vdatum $(vdatum)
endif

if defined dem
   arguments=$(arguments) --dem $(dem)
endif

# Set files to capture HTCondor log & standard error stream
logs_directory = $ENV(HOME)/logs/$(workflow)/$(site_code)_$(flight_date)
log = $(logs_directory)/HyPro_$(Cluster)_$(site_code)_$(flight_date)_$(line_number).log
error = $(logs_directory)/HyPro_$(Cluster)_$(site_code)_$(flight_date)_$(line_number).err

# Copy over bash utilities to worker node
transfer_input_files = $ENV(CHTC_REPO)/utils,\
 $ENV(ENSPEC_REPO)/src,\
 $ENV(CHTC_REPO)/source/$(workflow)2/deploy.py,\
 $ENV(CHTC_REPO)/source/$(workflow)2/template.py,\
 $ENV(CHTC_REPO)/source/$(workflow)2/sitecustomize.py.jinja

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_disk = $(disk)
request_memory = $(memory)

queue
