# impute.sub
universe = vanilla

# IMPORTANT! Require execute servers that have access to Staging
requirements = (TARGET.OpSysMajorVer >= 8) && (TARGET.HasCHTCStaging == TRUE)

executable = $ENV(CHTC_REPO)/source/impute/impute.sh
arguments = $(basename)

# Set files to capture HTCondor log & standard error stream
logs_directory = $ENV(HOME)/logs/impute/$(basename)
log = $(logs_directory)/Impute_$(Cluster)_$(basename).log
error = $(logs_directory)/Impute_$(Cluster)_$(basename).err

# Copy over bash utilities & Python source code to worker node
transfer_input_files = $ENV(CHTC_REPO)/utils, $ENV(ENSPEC_REPO)/src

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_disk = 35GB
request_memory = 30GB

if defined threshold
   arguments=$(arguments) --threshold $(threshold)
endif

if !$(ransac:0)
      arguments=$(arguments) --no-ransac
endif

if defined precomputed
    environment = "PRECOMPUTED_RADIANCE=$(precomputed)"
endif

queue
