# impute.sub
universe = vanilla

# IMPORTANT! Require execute servers that have access to Staging
requirements = (TARGET.OpSysMajorVer >= 8) && (TARGET.HasCHTCStaging == TRUE)

executable = $ENV(CHTC_REPO)/source/impute/impute.sh
arguments = $(basename)

# Handle optional command-line arguments from `condor_submit`
include : $ENV(CHTC_REPO)/arguments/optional.sh --threshold threshold |
include : $ENV(CHTC_REPO)/arguments/optional.sh --ftest alpha |
include : $ENV(CHTC_REPO)/arguments/optional.sh --count frames |
include : $ENV(CHTC_REPO)/arguments/optional.sh --precomputed precomputed |
include : $ENV(CHTC_REPO)/arguments/unflag.sh --no-ransac ransac |

if defined out
    # NOTE: `output` is an HTCondor Submit command
    environment = "OUTPUT_DIRECTORY=$(out)"
endif

# Set files to capture HTCondor log & standard error stream
logs_directory = $ENV(HOME)/logs/impute/$(basename)
log = $(logs_directory)/Impute_$(Cluster)_$(basename).log
error = $(logs_directory)/Impute_$(Cluster)_$(basename).err

# Copy over bash utilities & Python source code to worker node
transfer_input_files = $ENV(CHTC_REPO)/utils, $ENV(ENSPEC_REPO)/src

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_disk = 35GB
request_memory = 30GB

queue
