# interact.sub

universe = vanilla

# Direct log, standard error & output streams to files
log = $ENV(HOME)/logs/test/interactive_$(Cluster).log
error = $ENV(HOME)/logs/test/interactive_$(Cluster).err
output = $ENV(HOME)/logs/test/interactive_$(Cluster).out

# IMPORTANT! Require execute servers that have access to Staging
requirements = (TARGET.HasCHTCStaging == TRUE)

transfer_input_files = $ENV(CHTC_REPO)/utils, $ENV(ENSPEC_REPO)/src

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_memory = $(memory:1GB)
request_disk = $(disk:1GB)

if !defined request_cpus
   request_cpus = 1
endif

queue
