# merge.sub
universe = vanilla
+Category = "MergeLUT:$(tile)"

# IMPORTANT! Require execute servers that have access to Staging
requirements = (TARGET.OpSysMajorVer >= 8) && (TARGET.HasCHTCStaging == TRUE)

# TODO: Pass environment variables to sub-DAGs?

# Specify executable
executable = git/hypro-chtc/source/libradtran/merge/merge.sh
arguments = $(tile)

# Set files to capture HTCondor log & standard error stream
log = logs/lut/merge_$(tile)_$(Cluster).log
error = logs/lut/merge_$(tile)_$(Cluster).err
output = logs/lut/merge_$(tile)_$(Cluster).out

# Copy over bash utilities to worker node
transfer_input_files = git/hypro-chtc/utils, git/enspec/src

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_disk = 15GB
request_memory = 4GB

queue
