# testing.sub
universe = vanilla

# IMPORTANT! Require execute servers that have access to Staging
requirements = (TARGET.OpSysMajorVer >= 8) && (TARGET.HasCHTCStaging == TRUE)

# Specify executable
executable = source/testing/testing.sh

# Pass HTCondor job ID as environment variable
environment = CONDOR_JOB_ID=$(Cluster).$(Process)

# Set files to capture log & standard error stream
log = $ENV(HOME)/logs/test/testing_$(Cluster).log
error = $ENV(HOME)/logs/test/testing_$(Cluster).err

transfer_input_files = $ENV(HOME)/utils

request_cpus = 1
request_disk = $(disk)
request_memory = $(memory)

queue
