# modtran.sub
universe = vanilla

# Specify executable
executable = source/modtran/modtran.sh
# arguments =

concurrency_limits = MODTRAN:4

# Set files to capture HTCondor log & standard error stream
logs_directory = $ENV(HOME)/logs/modtran
log = $(logs_directory)/MODTRAN_$(Cluster).log
error = $(logs_directory)/MODTRAN_$(Cluster).err

# Copy over bash utilities to worker node
transfer_input_files = $ENV(HOME)/utils

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_disk =
request_memory =

queue
